---
name: App-ZofCMS-Plugin-CSSMinifier
version: 0.0104
author:
  - "'Zoffix <'zoffix@cpan.org'>"
abstract: plugin for minifying CSS files
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  App::ZofCMS::Plugin::Base: 0.0103
  CSS::Minifier: 0.01
configure_requires:
  Module::Build: 0.34
provides:
  App::ZofCMS::Plugin::CSSMinifier:
    file: lib/App/ZofCMS/Plugin/CSSMinifier.pm
    version: 0.0104
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
